CREATE FUNCTION MediaAvaliacao(int)
RETURNS REAL AS $$
DECLARE 
	Codigo ALIAS FOR $1;
	Media REAL;
BEGIN
	SELECT INTO Media AVG(Pontuacao) 
	FROM CRITERIO_AVALIACAO 
	WHERE CodAvaliacao= Codigo;
	RETURN Media;
END $$
LANGUAGE PLPGSQL;



CREATE OR REPLACE FUNCTION CalculaMediaAvaliacao()
RETURNS TRIGGER AS $$
DECLARE
	
BEGIN
	UPDATE AVALIACAO_ALUNO_PROFESSOR SET 
	Media= MediaAvaliacao(NEW.CodAvaliacao) 
	WHERE CodAvaliacao = NEW.CodAvaliacao;
	RETURN NULL;
END $$
LANGUAGE PLPGSQL;

CREATE TRIGGER InsercaoCriterios
AFTER INSERT OR UPDATE ON CRITERIO_AVALIACAO
FOR EACH ROW
EXECUTE PROCEDURE CalculaMediaAvaliacao();



CREATE OR REPLACE FUNCTION NotaProfessor(VARCHAR)
RETURNS REAL AS $$
DECLARE
	Matricula ALIAS FOR $1;
	Nota REAL;
BEGIN
	SELECT INTO Nota AVG(Media) FROM AVALIACAO_ALUNO_PROFESSOR 
	WHERE MatProfessor = Matricula;
	RETURN Nota;
END $$
LANGUAGE PLPGSQL;

CREATE FUNCTION CalculaNotaProfessor()
RETURNS TRIGGER AS $$
BEGIN
	UPDATE PROFESSOR SET Nota = NotaProfessor(OLD.MatProfessor)
	WHERE Matricula = OLD.MatProfessor;
	RETURN NULL;
END $$
LANGUAGE PLPGSQL;

CREATE TRIGGER AtualizaNota
AFTER UPDATE ON AVALIACAO_ALUNO_PROFESSOR
FOR EACH ROW
EXECUTE PROCEDURE CalculaNotaProfessor();
